name: xai_env
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - torch
    - torchvision
    - git+https://github.com/facebookresearch/sam2.git
    - replicate
    - pycocotools
    - Pillow
    - numpy
    - scikit-image
    - scikit-learn
    - requests
    - opencv-python
    - lpips